export const LABELS = {
  firstName: 'First name',
  lastName: 'Last name',
  userName: 'Username',
  email: 'Email',
  createAnAccount: 'Create an account',
  password: 'Password',
  resetPassword: 'Reset Password',
  confirmPassword: 'Confirm Password',
  verificationCode: 'Verification Code',
  signIn: 'Sign in',
  signUp: 'Sign up',
  enterNewPassword: 'Enter New Password',
  forgotPassword: 'Forgot password?',
  forgotPassword2: 'Forgot Password?',
  dontHaveAccount: "Don't have an account? ",
  haveAccount: 'Already have an account? ',
  sendCode: 'Send code',
  checkYourEmail: 'Please check your email',
  submit: 'Submit',
  didntReceiveCode: "Didn't receive code yet?",
  resend: 'Resend',
  changePassword: 'Change Password',
  newPassword: 'New Password',
  confirmPass: 'Confirm Password',
  currentPassword: 'Current Password',
  search: 'Search',
  edit: 'Edit',
  delete: 'Delete',
  settings: 'Settings',
  logout: 'Logout',
  deleteAcc: 'Delete Account',
  verifyPassword: 'Verify Password',
  allowNoti: 'Allow Notifications',
  no: 'No',
  wantLogout: 'Are you sure, do you want to logout?',
  yes: 'Yes',
  wantDelete: 'Are you sure, do you want to delete your account?',
  noData: 'No data available',
  cancel: 'Cancel',
  discard: 'Discard',
  saveSmall: 'Save',
  keep: 'Keep',
  leaveChg: 'Are you sure you want to leave without saving your changes?',
};
